# Generated by Django 3.1.1 on 2020-09-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='post_image')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
