# Generated by Django 3.1.1 on 2020-09-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/post_image'),
        ),
    ]
